### ISSUE TITLE
migrate nms4r functions and vignettes to infographiqR

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiqR#60]
Migrate vignettes:

* [Introduction](https://noaa-onms.github.io/nms4r/articles/Introduction.html)
* [Creating a new Infographic Website](https://noaa-onms.github.io/nms4r/articles/Overview.html)
* [Reporting Functions](https://noaa-onms.github.io/nms4r/articles/Reporting.html)

Migrate functions:
* [Function reference • nms4r](https://noaa-onms.github.io/nms4r/reference/index.html)
  ![image](https://user-images.githubusercontent.com/2837257/116714944-1acb2000-a98b-11eb-99d7-415fbcc06cdf.png)

**Comment by bbest** [comment]
Hey @superjai,

We discussed switching the documentation of infographiq from **pkgdown** for an R package to a looser **bookdown** format, but considering these nms4r functions and other R helpers, I advocate sticking to pkgdown with vignettes to describe use without R.

**Comment by bbest** [comment]
On pkgdown website [marinebon.org/infographiqR](https://marinebon.org/infographiqR/) and README now seeing:

![image](https://user-images.githubusercontent.com/2837257/118032392-7cd93d00-b31c-11eb-95fd-171d332b7585.png)

This is because of old dependencies that need to get fixed with `nms4r` R package renamed to [`onmsR`](https://noaa-onms.github.io/onmsR/).

For more details, check the **Github Action** logs, like [@5a87146](https://github.com/marinebon/infographiqR/runs/2569247980?check_suite_focus=true):

```
Reading 'vignettes/Introduction.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 11-16 (Introduction.Rmd) 
Error: Error in library(nms4r) : there is no package called 'nms4r'
```

**Comment by superjai** [comment]
Hey @bbest - I am still having trouble getting the new infographiqjs functionality working within cinms.

I have updated the file [_svg-html_child.Rmd ](https://github.com/noaa-onms/cinms/blob/master/_svg-html_child.Rmd) to point to the new versions of the javascript. I used the following [working infographic example](https://noaa-iea.github.io/fk-esr-info/template_infographic.html) as the template of which javascript libraries to point to. I then reknitted [kelp forest](https://github.com/noaa-onms/cinms/blob/master/kelp-forest.Rmd) as a test. If you take a look at the [associated html file](https://github.com/noaa-onms/cinms/blob/master/kelp-forest.html), you'll see that none of the svg functions are working (highlighting, modal window pop up, etc.).

Not sure what the issue is, but I have been going around and around on this.

**Comment by bbest** [comment]
Hi Jai, 

Let's move this discussion over to the CINMS issue to get it working: https://github.com/noaa-onms/cinms/issues/80

Although getting there clearly has implications for this repo.
