### ISSUE TITLE
+ Rmarkdown template(s) for infographiq website (& modals)

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiqR#64]
It would be pretty cool if we getting started with an infographiq website could be as simple as navigating from RStudio's menu File > New File > Rmarkdown... From Template:

See: [R Markdown Document Templates](https://rstudio.github.io/rstudio-extensions/rmarkdown_templates.html)

![](https://rstudio.github.io/rstudio-extensions/resources/rmarkdown_templates/images/new_r_markdown.png)

**Comment by bbest** [comment]
Or perhaps RStudio menu File > New Project... New Directory [RStudio Project Templates](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html) are better suited for multiple files:

![](https://rstudio.github.io/rstudio-extensions/resources/project_templates/images/template_menu.png)

**Comment by superjai** [comment]
Hey @bbest - completed.

I created a new function in render_rmd.R called [infographiq_template()](https://github.com/marinebon/infographiqR/blob/3e9950538e640ee3f2d17b214d26fafd87ea1aa0/R/render_rmd.R#L320) that copies the template version of the website to the desired directory. 

This template is located in the directory: [infographiqR/inst/template_website/](https://github.com/marinebon/infographiqR/tree/master/inst/template_website). Please note that there is a very similarly named directory in inst called [site_template](https://github.com/marinebon/infographiqR/tree/master/inst/site_template). I don't know what this directory is and it is quite old (latest changes are 3 years old) - I am guessing that it should be deleted.

This template site is extremely similar to the example site in the guide I wrote, so that my guide can be used in this context.

There is also a file in the directory infographiqR/inst/rstudio/templates/project/ called [infographiq_template.dcf](https://github.com/marinebon/infographiqR/blob/master/inst/rstudio/templates/project/infographiq_template.dcf). This .dcf file adds the `infographiq_template()` functionality to the New Project screen in RStudio:

![Screen Shot 2021-07-26 at 3 10 18 AM](https://user-images.githubusercontent.com/1744300/126972543-673e6869-ab36-446b-8808-6eddb75852a6.png)

In order to see this in the New Project screen in your version of RStudio, you'll need to: 1) update your installation of infographiqR, 2) close RStudio, 3) reopen RStudio.
